### ISSUE TITLE
为什么性能会提升这么大呢

### ISSUE THREAD

**Issue by zfyu222** [breezechen/fast_mutex#2]
没有弄懂为什么相比传统的lock会提升这么大，这里互斥的时候，也会切换线程，而且还会定期切回来查看。而传统的lock的工作看上去更加科学，直接休眠，然后中间不会再切回来看（会占用cpu），直到锁被释放才会唤醒。但是奇怪的是传统的lock反而比这个慢很多，看完了fast_mutex的源码也没明白高性能的道理，可否告知一下呢？

**Comment by breezechen** [comment]
不好意思，长时间没上github。
所谓性能提升之类的，可能是因为其他实现考虑的东西太多，比如重入等问题，而且readme里面的测试也不公平。
`fast_mutex`的使用场景是不想引入pthread或boost等依赖，include一个h文件就能编译是它的主要目的。
`sleep(1 ms)`刚好是这个需求下最理想的解决方案，自旋的时候让出cpu，1ms的间隔也不算太长。
